### ISSUE TITLE
数据集请求

### ISSUE THREAD

**Issue by wangchaoqiang** [NinaTian98369/Double-propagation#1]
您好：
我看到这份代码里有一个亚马逊的数据集，按您代码的描述应该是标注好了观点目标和观点词的。想问下这份数据集可以在哪里下载。

![image](https://user-images.githubusercontent.com/45144490/65371175-6b4ca880-dc93-11e9-8a78-4f36abb4b5ce.png)

**Comment by NinaTian98369** [comment]
你好，这个是使用StanfordCoreNLP得到的，并非公开数据，谢谢你的提问。

**Comment by NinaTian98369** [comment]
您好，补充了几个您可能需要的文件。请查看repo主页新增的amazon文件夹

**Comment by wangchaoqiang** [comment]
您好，您给的数据集链接好像访问不了，翻墙好像也访问不了，谢谢。

**Comment by NinaTian98369** [comment]
That link should be accessible via a VPN if you are visiting from China. Please email me (tyf16 AT mails.tsinghua.edu.cn) to get a direct copy.
